classdef Squeeze_To_AddLayer1028 < nnet.layer.Layer & nnet.layer.Formattable
    % A custom layer auto-generated while importing an ONNX network.
    
    %#codegen
    %#ok<*PROPLC>
    %#ok<*NBRAK>
    %#ok<*INUSL>
    %#ok<*VARARG>
    
    properties (Learnable)
        axes_const__508__539
        sequential_55_den_2
        sequential_55_den_6
        sequential_55_seq_21
    end
    
    properties
        ONNXParams         % An ONNXParameters object containing parameters used by this layer.
    end
    
    methods
        function this = Squeeze_To_AddLayer1028(name, onnxParams)
            this.Name = name;
            this.OutputNames = {'dense_63'};
            this.ONNXParams = onnxParams;
            this.axes_const__508__539 = onnxParams.Learnables.axes_const__508__539;
            this.sequential_55_den_2 = onnxParams.Learnables.sequential_55_den_2;
            this.sequential_55_den_6 = onnxParams.Learnables.sequential_55_den_6;
            this.sequential_55_seq_21 = onnxParams.Learnables.sequential_55_seq_21;
        end
        
        function [dense_63] = predict(this, sequential_55_seq_34)
            if isdlarray(sequential_55_seq_34)
                sequential_55_seq_34 = stripdims(sequential_55_seq_34);
            end
            sequential_55_seq_34NumDims = 4;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.axes_const__508__539 = this.axes_const__508__539;
            onnxParams.Learnables.sequential_55_den_2 = this.sequential_55_den_2;
            onnxParams.Learnables.sequential_55_den_6 = this.sequential_55_den_6;
            onnxParams.Learnables.sequential_55_seq_21 = this.sequential_55_seq_21;
            [dense_63, dense_63NumDims] = Squeeze_To_AddFcn(sequential_55_seq_34, sequential_55_seq_34NumDims, onnxParams, 'Training', false, ...
                'InputDataPermutation', {[4 3 1 2], ['as-is']}, ...
                'OutputDataPermutation', {['as-is'], ['as-is']});
            if any(cellfun(@(A)isempty(A)||~isnumeric(A), {dense_63}))
                fprintf('Runtime error in network. The custom layer ''%s'' output an empty or non-numeric value.\n', 'Squeeze_To_AddLayer1028');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Squeeze_To_AddLayer1028'));
            end
            dense_63 = dlarray(single(dense_63), repmat('U', 1, max(2, dense_63NumDims)));
            if ~coder.target('MATLAB')
                dense_63 = extractdata(dense_63);
            end
        end
        
        function [dense_63] = forward(this, sequential_55_seq_34)
            if isdlarray(sequential_55_seq_34)
                sequential_55_seq_34 = stripdims(sequential_55_seq_34);
            end
            sequential_55_seq_34NumDims = 4;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.axes_const__508__539 = this.axes_const__508__539;
            onnxParams.Learnables.sequential_55_den_2 = this.sequential_55_den_2;
            onnxParams.Learnables.sequential_55_den_6 = this.sequential_55_den_6;
            onnxParams.Learnables.sequential_55_seq_21 = this.sequential_55_seq_21;
            [dense_63, dense_63NumDims] = Squeeze_To_AddFcn(sequential_55_seq_34, sequential_55_seq_34NumDims, onnxParams, 'Training', true, ...
                'InputDataPermutation', {[4 3 1 2], ['as-is']}, ...
                'OutputDataPermutation', {['as-is'], ['as-is']});
            if any(cellfun(@(A)isempty(A)||~isnumeric(A), {dense_63}))
                fprintf('Runtime error in network. The custom layer ''%s'' output an empty or non-numeric value.\n', 'Squeeze_To_AddLayer1028');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Squeeze_To_AddLayer1028'));
            end
            dense_63 = dlarray(single(dense_63), repmat('U', 1, max(2, dense_63NumDims)));
            if ~coder.target('MATLAB')
                dense_63 = extractdata(dense_63);
            end
        end
    end
end

function [dense_63, dense_63NumDims, state] = Squeeze_To_AddFcn(sequential_55_seq_34, sequential_55_seq_34NumDims, params, varargin)
%SQUEEZE_TO_ADDFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 14
%
% Variable names in this function are taken from the original ONNX file.
%
% [DENSE_63] = Squeeze_To_AddFcn(SEQUENTIAL_55_SEQ_34, PARAMS)
%			- Evaluates the imported ONNX network SQUEEZE_TO_ADDFCN with input(s)
%			SEQUENTIAL_55_SEQ_34 and the imported network parameters in PARAMS. Returns
%			network output(s) in DENSE_63.
%
% [DENSE_63, STATE] = Squeeze_To_AddFcn(SEQUENTIAL_55_SEQ_34, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = Squeeze_To_AddFcn(SEQUENTIAL_55_SEQ_34, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% SEQUENTIAL_55_SEQ_34
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  SEQUENTIAL_55_SEQ_34:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% DENSE_63
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  DENSE_63:		[unk__571, 2]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[sequential_55_seq_34, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(sequential_55_seq_34, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'sequential_55_seq_34'}, {sequential_55_seq_34}, [sequential_55_seq_34NumDims]);
% Call the top-level graph function:
[dense_63, dense_63NumDims, state] = Squeeze_To_AddGraph1024(sequential_55_seq_34, NumDims.sequential_55_seq_34, Vars, NumDims, Training, params.State);
% Postprocess the output data
[dense_63] = postprocessOutput(dense_63, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [dense_63, dense_63NumDims1027, state] = Squeeze_To_AddGraph1024(sequential_55_seq_34, sequential_55_seq_34NumDims1026, Vars, NumDims, Training, state)
% Function implementing the graph 'Squeeze_To_AddGraph1024'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.sequential_55_seq_34 = sequential_55_seq_34;
NumDims.sequential_55_seq_34 = sequential_55_seq_34NumDims1026;

% Execute the operators:
% Squeeze:
[Vars.sequential_55_seq_37, NumDims.sequential_55_seq_37] = onnxSqueeze(Vars.sequential_55_seq_34, Vars.axes_const__508__539, NumDims.sequential_55_seq_34);

% Transpose:
[perm, NumDims.sequential_55_seq_36] = prepareTransposeArgs(Vars.TransposePerm1025, NumDims.sequential_55_seq_37);
if ~isempty(perm)
    Vars.sequential_55_seq_36 = permute(Vars.sequential_55_seq_37, perm);
end

% Reshape:
[shape, NumDims.sequential_55_seq_24] = prepareReshapeArgs(Vars.sequential_55_seq_36, Vars.const_fold_opt__547, NumDims.sequential_55_seq_36, 0);
Vars.sequential_55_seq_24 = reshape(Vars.sequential_55_seq_36, shape{:});

% MatMul:
[Vars.sequential_55_seq_22, NumDims.sequential_55_seq_22] = onnxMatMul(Vars.sequential_55_seq_24, Vars.sequential_55_seq_21, NumDims.sequential_55_seq_24, NumDims.sequential_55_seq_21);

% Add:
Vars.sequential_55_seq_20 = Vars.sequential_55_seq_22 + Vars.sequential_55_seq_19;
NumDims.sequential_55_seq_20 = max(NumDims.sequential_55_seq_22, NumDims.sequential_55_seq_19);

% Relu:
Vars.sequential_55_seq_23 = relu(Vars.sequential_55_seq_20);
NumDims.sequential_55_seq_23 = NumDims.sequential_55_seq_20;

% MatMul:
[Vars.sequential_55_den_3, NumDims.sequential_55_den_3] = onnxMatMul(Vars.sequential_55_seq_23, Vars.sequential_55_den_2, NumDims.sequential_55_seq_23, NumDims.sequential_55_den_2);

% Add:
Vars.sequential_55_den_1 = Vars.sequential_55_den_3 + Vars.sequential_55_dense_;
NumDims.sequential_55_den_1 = max(NumDims.sequential_55_den_3, NumDims.sequential_55_dense_);

% Relu:
Vars.sequential_55_den_4 = relu(Vars.sequential_55_den_1);
NumDims.sequential_55_den_4 = NumDims.sequential_55_den_1;

% MatMul:
[Vars.sequential_55_den_7, NumDims.sequential_55_den_7] = onnxMatMul(Vars.sequential_55_den_4, Vars.sequential_55_den_6, NumDims.sequential_55_den_4, NumDims.sequential_55_den_6);

% Add:
Vars.dense_63 = Vars.sequential_55_den_7 + Vars.sequential_55_den_5;
NumDims.dense_63 = max(NumDims.sequential_55_den_7, NumDims.sequential_55_den_5);

% Set graph output arguments from Vars and NumDims:
dense_63 = Vars.dense_63;
dense_63NumDims1027 = NumDims.dense_63;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(sequential_55_seq_34, numDataOutputs, params, varargin)
% Function to validate inputs to Squeeze_To_AddFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'sequential_55_seq_34', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, sequential_55_seq_34, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [sequential_55_seq_34, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(sequential_55_seq_34, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(sequential_55_seq_34, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {sequential_55_seq_34}));
% Make the input variables into unlabelled dlarrays:
sequential_55_seq_34 = makeUnlabeledDlarray(sequential_55_seq_34);
% Permute inputs if requested:
sequential_55_seq_34 = permuteInputVar(sequential_55_seq_34, inputDataPerms{1}, 4);
end

function [dense_63] = postprocessOutput(dense_63, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(dense_63)
        dense_63 = extractdata(dense_63);
    end
end
% Permute outputs if requested:
dense_63 = permuteOutputVar(dense_63, outputDataPerms{1}, 2);
end


%% dlarray functions implementing ONNX operators:

function [D, numDimsD] = onnxMatMul(A, B, numDimsA, numDimsB)
% Implements the ONNX MatMul operator.

% If either arg is more than 2D, loop over all dimensions before the final
% 2. Inside the loop, perform matrix multiplication.

% If B is 1-D, temporarily extend it to a row vector
if numDimsB==1
    B = B(:)';
end
maxNumDims = max(numDimsA, numDimsB);
numDimsD = maxNumDims;
if maxNumDims > 2
    % sizes of matrices to be multiplied
    matSizeA        = size(A, 1:2);
    matSizeB        = size(B, 1:2);
    % size of the stack of matrices
    stackSizeA      = size(A, 3:maxNumDims);
    stackSizeB      = size(B, 3:maxNumDims);
    % final stack size
    resultStackSize = max(stackSizeA, stackSizeB);
    % full implicitly-expanded sizes
    fullSizeA       = [matSizeA resultStackSize];
    fullSizeB       = [matSizeB resultStackSize];
    resultSize      = [matSizeB(1) matSizeA(2) resultStackSize];
    % Repmat A and B up to the full stack size using implicit expansion
    A = A + zeros(fullSizeA);
    B = B + zeros(fullSizeB);
    % Reshape A and B to flatten the stack dims (all dims after the first 2)
    A2 = reshape(A, size(A,1), size(A,2), []);
    B2 = reshape(B, size(B,1), size(B,2), []);
    % Iterate down the stack dim, doing the 2d matrix multiplications
    D2 = zeros([matSizeB(1), matSizeA(2), size(A2,3)], 'like', A);
    for i = size(A2,3):-1:1
        D2(:,:,i) = B2(:,:,i) * A2(:,:,i);
    end
    % Reshape D2 to the result size (unflatten the stack dims)
    D = reshape(D2, resultSize);
else
    D = B * A;
    if numDimsA==1 || numDimsB==1
        D = D(:);
        numDimsD = 1;
    end
end
end

function [Y, numDimsY] = onnxSqueeze(X, ONNXAxes, numDimsX)
% Implements the ONNX Squeeze operator
if numDimsX == 0
    Y = X;
    numDimsY = numDimsX;
else
    % Find the new ONNX shape
    curOShape = size(X, numDimsX:-1:1);
    if isempty(ONNXAxes)
        newOShape = curOShape(curOShape ~= 1);
    else
        ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsX;
        newOShape = curOShape;
        newOShape(ONNXAxes+1) = [];
    end
    % Get numDimsY from ONNX shape
    numDimsY  = numel(newOShape);
    newMShape = [fliplr(newOShape) ones(1, 2-numDimsY)];    % Append 1's to shape if numDims<2
    Y         = reshape(X, newMShape);
end
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX, allowzero)
% Prepares arguments for implementing the ONNX Reshape operator
ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged" if allowzero is false, and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size if allowzero is true
if any(ONNXShape==0) && allowzero==0
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [perm, numDimsA] = prepareTransposeArgs(ONNXPerm, numDimsA)
% Prepares arguments for implementing the ONNX Transpose operator
if numDimsA <= 1        % Tensors of numDims 0 or 1 are unchanged by ONNX Transpose.
    perm = [];
else
    if isempty(ONNXPerm)        % Empty ONNXPerm means reverse the dimensions.
        perm = numDimsA:-1:1;
    else
        perm = numDimsA-flip(ONNXPerm);
    end
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.
if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more
    
    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);
    
    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end
    
    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);
    
    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));
    
    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;
    
    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray
if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)
% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in t.
for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
